# Generated by Django 2.0.5 on 2018-09-06 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_auto_20180906_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=100)),
                ('dead_line', models.CharField(blank=True, max_length=50, null=True)),
                ('date_requested', models.CharField(blank=True, max_length=50, null=True)),
                ('sku_count', models.CharField(blank=True, max_length=100)),
                ('sell_sheet', models.BooleanField(default=True)),
                ('pog_render', models.BooleanField(default=True)),
                ('artwork_design', models.BooleanField(default=True)),
                ('mockup', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, max_length=5000)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.Category')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.EmployeeList')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.Status')),
            ],
        ),
    ]
