# Generated by Django 2.0.5 on 2018-09-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20180907_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackheader',
            name='date_requested',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trackheader',
            name='dead_line',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
