# Generated by Django 2.0.5 on 2018-09-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20180907_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackheader',
            name='id',
        ),
        migrations.AddField(
            model_name='trackheader',
            name='report_key',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
