# Generated by Django 2.0.5 on 2018-09-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20180907_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackheader',
            name='report_key',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
