# Generated by Django 2.0.5 on 2018-09-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20180907_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackheader',
            options={},
        ),
    ]
