# Generated by Django 2.0.5 on 2018-09-07 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180906_1641'),
        ('report', '0009_remove_trackheader_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackheader',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_by', to='employee.EmployeeList'),
        ),
    ]
