# Generated by Django 2.0.5 on 2018-09-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_trackheader_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackheader',
            name='date_requested',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trackheader',
            name='dead_line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
