# Generated by Django 2.0.5 on 2018-09-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20180907_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackheader',
            name='task_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
