# Generated by Django 2.0.5 on 2018-09-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20180913_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackheader',
            options={},
        ),
    ]
