# Generated by Django 2.0.5 on 2018-09-13 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20180913_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_design', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='mockup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mockup', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PogRender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pog_render', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_sheet', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trackheader',
            name='artwork_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.ArtworkDesign'),
        ),
        migrations.AlterField(
            model_name='trackheader',
            name='mockup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.mockup'),
        ),
        migrations.AlterField(
            model_name='trackheader',
            name='pog_render',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.PogRender'),
        ),
        migrations.AlterField(
            model_name='trackheader',
            name='sell_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.SellSheet'),
        ),
    ]
