# Generated by Django 2.0.5 on 2018-09-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_auto_20180913_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackheader',
            name='test',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')], default=1),
            preserve_default=False,
        ),
    ]
