# Generated by Django 2.0.5 on 2018-09-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_trackheader_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackheader',
            name='test',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')], default=False),
        ),
    ]
