# Generated by Django 2.0.5 on 2018-09-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_auto_20180914_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackheader',
            name='test',
        ),
        migrations.AddField(
            model_name='trackheader',
            name='google_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trackheader',
            name='marklyn_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
