# Generated by Django 2.0.5 on 2018-09-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_auto_20180914_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackheader',
            name='google_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='trackheader',
            name='marklyn_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
