# Generated by Django 2.0.5 on 2018-09-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_auto_20180914_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackheader',
            name='google_url_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trackheader',
            name='marklyn_url_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
