# Generated by Django 2.0.5 on 2018-09-17 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_auto_20180914_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccomment',
            name='public_comments',
            field=models.CharField(blank=True, max_length=50000),
        ),
        migrations.AlterField(
            model_name='trackheader',
            name='mockup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.Mockup'),
        ),
    ]
