# Generated by Django 2.0.5 on 2018-09-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180911_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marklynuser',
            name='user_pic',
        ),
    ]
